### ISSUE TITLE
Add a little triangle to expand the text box. current one is too small

### ISSUE THREAD

**Issue by ElijahRus250** [DedicatedMC/Raw-Power-Panel#7] opened 2020-10-22 14:26 UTC
EXAMPLE: 
![Kapture 2020-10-22 at 10 25 25](https://user-images.githubusercontent.com/64851720/96885886-07c21b00-1451-11eb-85ff-f50c87880376.gif)

**Comment by TehloWasTaken** [comment] 2020-10-22 14:29
Oooh thatd be dope ❤️

**Comment by alliraine** [comment] 2020-10-23 00:57
What text box? you gotta be more descriptive @luckyywastaken

**Comment by ElijahRus250** [comment] 2020-10-23 18:03
in the file manager 
<img width="1168" alt="Screen Shot 2020-10-23 at 2 03 19 PM" src="https://user-images.githubusercontent.com/64851720/97038257-83e35e00-1538-11eb-8751-de39a7524d22.png">

**Comment by alliraine** [comment] 2020-11-02 13:34
Duplicate of #35

**Closed as completed by alliraine** 2020-11-02 13:34 UTC
Labels: enhancement, question

**Comment by ElijahRus250** [comment] 2020-11-04 20:19
When this was made before that one :(

**Comment by alliraine** [comment] 2020-11-04 20:20
I did it wrong. I'm sorry. :( Please forgive me

**Comment by ElijahRus250** [comment] 2020-11-04 20:32
its ok, you now must buy my only fans
