### ISSUE TITLE
File Editor Not Wrapping Long Lines

### ISSUE THREAD

**Issue by Fredthedoggy** [DedicatedMC/Raw-Power-Panel#65] opened 2021-12-12 15:56 UTC
**Describe the bug**
The RPP's file editor does not wrap lines that don't fit on your screen, but instead lets them continue off.
This means that the buttons above it for saving + the language selector are actually thrown off the screen

**To Reproduce**
Make a file (YAML in my case) in the Raw Power Panel, write a very long line.

**Expected behavior**
You should still see the save button on the upper right

**Screenshots**
![Gif](https://user-images.githubusercontent.com/45927799/145719444-28b49f3b-6b84-41ae-b9f3-c73bdbb92040.gif)

**Desktop Details**
 - OS `Windows 10`
 - Browser `Chrome`
 - Screen Resolution `1920x1080`

**Additional context**
N/A

**Comment by EgoMaw** [comment] 2022-01-20 14:28
Duplicate of #45

**Closed as completed by EgoMaw** 2022-01-20 14:28 UTC
Labels: bug
